/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.bible.Scripture', null, global);
goog.exportSymbol('proto.bible.ScriptureList', null, global);
goog.exportSymbol('proto.bible.Scriptures', null, global);
goog.exportSymbol('proto.bible.ScripturesList', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bible.Scripture = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bible.Scripture, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bible.Scripture.displayName = 'proto.bible.Scripture';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bible.Scripture.prototype.toObject = function(opt_includeInstance) {
  return proto.bible.Scripture.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bible.Scripture} msg The msg instance to transform.
 * @return {!Object}
 */
proto.bible.Scripture.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: msg.getId(),
    book: msg.getBook(),
    chapter: msg.getChapter(),
    verse: msg.getVerse(),
    scripture: msg.getScripture()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bible.Scripture}
 */
proto.bible.Scripture.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bible.Scripture;
  return proto.bible.Scripture.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bible.Scripture} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bible.Scripture}
 */
proto.bible.Scripture.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBook(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChapter(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVerse(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setScripture(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.bible.Scripture} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.bible.Scripture.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bible.Scripture.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.bible.Scripture.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = this.getBook();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getChapter();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = this.getVerse();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = this.getScripture();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.bible.Scripture} The clone.
 */
proto.bible.Scripture.prototype.cloneMessage = function() {
  return /** @type {!proto.bible.Scripture} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.bible.Scripture.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.bible.Scripture.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 book = 2;
 * @return {number}
 */
proto.bible.Scripture.prototype.getBook = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.bible.Scripture.prototype.setBook = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 chapter = 3;
 * @return {number}
 */
proto.bible.Scripture.prototype.getChapter = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.bible.Scripture.prototype.setChapter = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 verse = 4;
 * @return {number}
 */
proto.bible.Scripture.prototype.getVerse = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.bible.Scripture.prototype.setVerse = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string scripture = 5;
 * @return {string}
 */
proto.bible.Scripture.prototype.getScripture = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.bible.Scripture.prototype.setScripture = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bible.Scriptures = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bible.Scriptures, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bible.Scriptures.displayName = 'proto.bible.Scriptures';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bible.Scriptures.prototype.toObject = function(opt_includeInstance) {
  return proto.bible.Scriptures.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bible.Scriptures} msg The msg instance to transform.
 * @return {!Object}
 */
proto.bible.Scriptures.toObject = function(includeInstance, msg) {
  var f, obj = {
    scripturesMap: (f = msg.getScripturesMap(true)) ? f.toArray() : [],
    book: msg.getBook(),
    chapter: msg.getChapter(),
    verse: msg.getVerse()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bible.Scriptures}
 */
proto.bible.Scriptures.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bible.Scriptures;
  return proto.bible.Scriptures.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bible.Scriptures} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bible.Scriptures}
 */
proto.bible.Scriptures.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getScripturesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readString);
         });
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBook(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChapter(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVerse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.bible.Scriptures} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.bible.Scriptures.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bible.Scriptures.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.bible.Scriptures.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getScripturesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeString);
  }
  f = this.getBook();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getChapter();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = this.getVerse();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.bible.Scriptures} The clone.
 */
proto.bible.Scriptures.prototype.cloneMessage = function() {
  return /** @type {!proto.bible.Scriptures} */ (jspb.Message.cloneMessage(this));
};


/**
 * map<int32, string> scriptures = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,string>}
 */
proto.bible.Scriptures.prototype.getScripturesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,string>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * optional int32 book = 2;
 * @return {number}
 */
proto.bible.Scriptures.prototype.getBook = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.bible.Scriptures.prototype.setBook = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 chapter = 3;
 * @return {number}
 */
proto.bible.Scriptures.prototype.getChapter = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.bible.Scriptures.prototype.setChapter = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 verse = 4;
 * @return {number}
 */
proto.bible.Scriptures.prototype.getVerse = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.bible.Scriptures.prototype.setVerse = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bible.ScriptureList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bible.ScriptureList.repeatedFields_, null);
};
goog.inherits(proto.bible.ScriptureList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bible.ScriptureList.displayName = 'proto.bible.ScriptureList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bible.ScriptureList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bible.ScriptureList.prototype.toObject = function(opt_includeInstance) {
  return proto.bible.ScriptureList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bible.ScriptureList} msg The msg instance to transform.
 * @return {!Object}
 */
proto.bible.ScriptureList.toObject = function(includeInstance, msg) {
  var f, obj = {
    scripturelistList: jspb.Message.toObjectList(msg.getScripturelistList(),
    proto.bible.Scripture.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bible.ScriptureList}
 */
proto.bible.ScriptureList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bible.ScriptureList;
  return proto.bible.ScriptureList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bible.ScriptureList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bible.ScriptureList}
 */
proto.bible.ScriptureList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bible.Scripture;
      reader.readMessage(value,proto.bible.Scripture.deserializeBinaryFromReader);
      msg.getScripturelistList().push(value);
      msg.setScripturelistList(msg.getScripturelistList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.bible.ScriptureList} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.bible.ScriptureList.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bible.ScriptureList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.bible.ScriptureList.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getScripturelistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.bible.Scripture.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.bible.ScriptureList} The clone.
 */
proto.bible.ScriptureList.prototype.cloneMessage = function() {
  return /** @type {!proto.bible.ScriptureList} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Scripture scriptureList = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.bible.Scripture>}
 */
proto.bible.ScriptureList.prototype.getScripturelistList = function() {
  return /** @type{!Array.<!proto.bible.Scripture>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bible.Scripture, 1));
};


/** @param {Array.<!proto.bible.Scripture>} value  */
proto.bible.ScriptureList.prototype.setScripturelistList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.bible.ScriptureList.prototype.clearScripturelistList = function() {
  this.setScripturelistList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bible.ScripturesList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bible.ScripturesList.repeatedFields_, null);
};
goog.inherits(proto.bible.ScripturesList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.bible.ScripturesList.displayName = 'proto.bible.ScripturesList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bible.ScripturesList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bible.ScripturesList.prototype.toObject = function(opt_includeInstance) {
  return proto.bible.ScripturesList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bible.ScripturesList} msg The msg instance to transform.
 * @return {!Object}
 */
proto.bible.ScripturesList.toObject = function(includeInstance, msg) {
  var f, obj = {
    scriptureslistList: jspb.Message.toObjectList(msg.getScriptureslistList(),
    proto.bible.Scriptures.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bible.ScripturesList}
 */
proto.bible.ScripturesList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bible.ScripturesList;
  return proto.bible.ScripturesList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bible.ScripturesList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bible.ScripturesList}
 */
proto.bible.ScripturesList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bible.Scriptures;
      reader.readMessage(value,proto.bible.Scriptures.deserializeBinaryFromReader);
      msg.getScriptureslistList().push(value);
      msg.setScriptureslistList(msg.getScriptureslistList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.bible.ScripturesList} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.bible.ScripturesList.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bible.ScripturesList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.bible.ScripturesList.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getScriptureslistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.bible.Scriptures.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.bible.ScripturesList} The clone.
 */
proto.bible.ScripturesList.prototype.cloneMessage = function() {
  return /** @type {!proto.bible.ScripturesList} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Scriptures scripturesList = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.bible.Scriptures>}
 */
proto.bible.ScripturesList.prototype.getScriptureslistList = function() {
  return /** @type{!Array.<!proto.bible.Scriptures>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bible.Scriptures, 1));
};


/** @param {Array.<!proto.bible.Scriptures>} value  */
proto.bible.ScripturesList.prototype.setScriptureslistList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.bible.ScripturesList.prototype.clearScriptureslistList = function() {
  this.setScriptureslistList([]);
};


goog.object.extend(exports, proto.bible);
